// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/article/[category]/[id]" | "/category/[slug]" | "/foto-review" | "/gaming" | "/hr" | "/hr/article/[category]/[id]" | "/hr/category/[slug]" | "/milkyway-test" | "/review" | "/space-pro"
type AppRouteHandlerRoutes = "/api/agent" | "/api/editorial" | "/api/foto-review" | "/api/foto-review/img" | "/api/gaming/[...path]" | "/api/globe-pins" | "/api/image-pull" | "/api/image-regen" | "/api/publish-local" | "/api/review" | "/api/review/select-ending" | "/api/run-status" | "/api/run-tasks" | "/api/space/[...path]" | "/api/sync-github" | "/api/tasks" | "/api/transcribe" | "/api/upload-image"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/agent": {}
  "/api/editorial": {}
  "/api/foto-review": {}
  "/api/foto-review/img": {}
  "/api/gaming/[...path]": { "path": string[]; }
  "/api/globe-pins": {}
  "/api/image-pull": {}
  "/api/image-regen": {}
  "/api/publish-local": {}
  "/api/review": {}
  "/api/review/select-ending": {}
  "/api/run-status": {}
  "/api/run-tasks": {}
  "/api/space/[...path]": { "path": string[]; }
  "/api/sync-github": {}
  "/api/tasks": {}
  "/api/transcribe": {}
  "/api/upload-image": {}
  "/article/[category]/[id]": { "category": string; "id": string; }
  "/category/[slug]": { "slug": string; }
  "/foto-review": {}
  "/gaming": {}
  "/hr": {}
  "/hr/article/[category]/[id]": { "category": string; "id": string; }
  "/hr/category/[slug]": { "slug": string; }
  "/milkyway-test": {}
  "/review": {}
  "/space-pro": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
