var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_global-error/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__cc99bfcf._.js")
R.c("server/chunks/ssr/openclaw_workspace_tech-pulse-css_c52843ee._.js")
R.c("server/chunks/ssr/3a4cd_next_dist_48e2508c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__de78cf2d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__6d283f00._.js")
R.c("server/chunks/ssr/3a4cd_next_dist_9b495715._.js")
R.c("server/chunks/ssr/openclaw_workspace_tech-pulse-css_app_fb76feb5._.js")
R.c("server/chunks/ssr/9d98b_tech-pulse-css__next-internal_server_app__global-error_page_actions_94e8ee69.js")
R.m(724310)
module.exports=R.m(724310).exports
