// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/article/[category]/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/article/[category]/[id]">> = Specific
  const handler = {} as typeof import("../../app/article/[category]/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/category/[slug]">> = Specific
  const handler = {} as typeof import("../../app/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/foto-review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/foto-review">> = Specific
  const handler = {} as typeof import("../../app/foto-review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/gaming/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gaming">> = Specific
  const handler = {} as typeof import("../../app/gaming/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hr/article/[category]/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/article/[category]/[id]">> = Specific
  const handler = {} as typeof import("../../app/hr/article/[category]/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hr/category/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/category/[slug]">> = Specific
  const handler = {} as typeof import("../../app/hr/category/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hr/gaming/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr/gaming">> = Specific
  const handler = {} as typeof import("../../app/hr/gaming/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/hr/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/hr">> = Specific
  const handler = {} as typeof import("../../app/hr/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/milkyway-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/milkyway-test">> = Specific
  const handler = {} as typeof import("../../app/milkyway-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/review">> = Specific
  const handler = {} as typeof import("../../app/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/space-pro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/space-pro">> = Specific
  const handler = {} as typeof import("../../app/space-pro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agent">> = Specific
  const handler = {} as typeof import("../../app/api/agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/editorial/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/editorial">> = Specific
  const handler = {} as typeof import("../../app/api/editorial/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/foto-review/img/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/foto-review/img">> = Specific
  const handler = {} as typeof import("../../app/api/foto-review/img/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/foto-review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/foto-review">> = Specific
  const handler = {} as typeof import("../../app/api/foto-review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/gaming/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gaming/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/gaming/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/globe-pins/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/globe-pins">> = Specific
  const handler = {} as typeof import("../../app/api/globe-pins/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/image-pull/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/image-pull">> = Specific
  const handler = {} as typeof import("../../app/api/image-pull/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/image-regen/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/image-regen">> = Specific
  const handler = {} as typeof import("../../app/api/image-regen/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/publish-local/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/publish-local">> = Specific
  const handler = {} as typeof import("../../app/api/publish-local/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/review/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review">> = Specific
  const handler = {} as typeof import("../../app/api/review/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/review/select-ending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/review/select-ending">> = Specific
  const handler = {} as typeof import("../../app/api/review/select-ending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/run-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run-status">> = Specific
  const handler = {} as typeof import("../../app/api/run-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/run-tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run-tasks">> = Specific
  const handler = {} as typeof import("../../app/api/run-tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/space/[...path]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/space/[...path]">> = Specific
  const handler = {} as typeof import("../../app/api/space/[...path]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/sync-github/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/sync-github">> = Specific
  const handler = {} as typeof import("../../app/api/sync-github/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tasks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tasks">> = Specific
  const handler = {} as typeof import("../../app/api/tasks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/transcribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/transcribe">> = Specific
  const handler = {} as typeof import("../../app/api/transcribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/upload-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload-image">> = Specific
  const handler = {} as typeof import("../../app/api/upload-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
